# Your wrangler.toml file should look something like this:
name = "saraltech-project"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# WARNING: When running a production build locally using Wrangler, be aware that the .env file may be omitted. Therefore, ensure that you have the same environment variables in your wrangler.toml file.
# However, you don't have to include Drizzle environment unless you want to access `drizzle-kit` commands in the deployed code.
[vars]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "saral-transport" # When you create your D1 DB, you choose the name
database_id = "6409b7ad-0656-469c-840c-03d73ddbec20"
preview_database_id = "6409b7ad-0656-469c-840c-03d73ddbec20"
