name: Deploy

on:
  push:
    branches:
      - main

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.15.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Deploy
        run: |
          pnpm run pages:deploy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_USER_API_TOKEN: ${{ secrets.CF_USER_API_TOKEN }}
          DB_REMOTE_DATABASE_ID: ${{ secrets.DB_REMOTE_DATABASE_ID }}
